import BulbBotClient from "../structures/BulbBotClient";
import { ApplicationCommand, ApplicationCommandOptionTypes, ApplicationCommandOptionsChannelTypes, ApplicationCommandType, LocalCode } from "./types/ApplicationCommands";
import { discordApi, developerGuild } from "../Config";
import axios from "axios";

export async function registerSlashCommands(client: BulbBotClient) {
	const isDev = process.env.ENVIRONMENT === "dev";

	const options: any = {
		method: "PUT",
		url: `${discordApi}/applications/${client.user?.id}/${isDev ? `guilds/${developerGuild}/` : ""}commands`,
		headers: {
			"Content-Type": "application/json",
			Authorization: `Bot ${process.env.TOKEN}`,
		},
		data: [...ChatInputCommand, ...UserCommand, ...MessageCommand],
	};

	try {
		const response = await axios.request(options);
		client.log.info(`[APPLICATION COMMANDS] Registered all of the slash commands, amount: ${response.data.length}`);
	} catch (err: any) {
		client.log.error(`[APPLICATION COMMANDS] Failed to register slash commands: ${err.response.statusText} (${err})`);
	}
}

function makeid(length) {
	let result = "";
	const characters = "abcdefghijklmnopqrstuvwxyz0123456789";
	const charactersLength = characters.length;
	for (let i = 0; i < length; i++) {
		result += characters.charAt(Math.floor(Math.random() * charactersLength));
	}
	return result;
}

function translate(_key: string) {
	const TRANSLATED_LANGS: LocalCode[] = ["es-ES", "hu", "fr", "cs", "sv-SE", "hi"];
	const obj = {};

	for (let i = 0; i < TRANSLATED_LANGS.length; i++) {
		/*obj[TRANSLATED_LANGS[i]] = i18next.t(key, {
			lng: TRANSLATED_LANGS[i],
		});*/
		obj[TRANSLATED_LANGS[i]] = makeid(32);
	}
	return obj;
}

export const ChatInputCommand: ApplicationCommand[] = [
	{
		name: "about",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Returns more information about the bot",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
	},
	{
		name: "commands",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Return a list of all available commands for Bulbbot",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
	},
	{
		name: "github",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Returns the GitHub repository link",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
	},
	{
		name: "help",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Gets useful information about the provided command",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "command",
				description: "The command you want to get more information for",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				type: ApplicationCommandOptionTypes.STRING,
				required: true,
			},
		],
	},
	{
		name: "invite",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Returns the invite link for the bot and the support server",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
	},
	{
		name: "license",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Returns the license file for the Github repo for the bot",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
	},
	{
		name: "ping",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Returns the API and WebSocket latency",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
	},
	{
		name: "privacypolicy",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Returns the Privacy Policy for the bot",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
	},
	{
		name: "uptime",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Returns the current uptime of the bot",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
	},

	{
		name: "channelinfo",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Returns information about the channel",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "channel",
				description: "The channel you want to get information about",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				type: ApplicationCommandOptionTypes.CHANNEL,
				required: true,
			},
		],
	},
	{
		name: "charinfo",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Returns information about the characters provided",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "string",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The characters you want to info",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
		],
	},
	{
		name: "inviteinfo",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Returns some useful info about a server from the invite link",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "invite",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The invite link of the server you want to info",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
		],
	},
	{
		name: "messageinfo",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Returns information about the message provided",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "message",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The message you want to get info about",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
		],
	},
	{
		name: "roleinfo",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Returns information about the role provided",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "role",
				type: ApplicationCommandOptionTypes.ROLE,
				description: "The role you want to get info about",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
		],
	},
	{
		name: "server",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Returns some useful information about the current server",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
	},
	{
		name: "userinfo",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Returns some useful info about a user",
		options: [
			{
				name: "user",
				type: ApplicationCommandOptionTypes.USER,
				description: "The user you want to info",
				required: false,
			},
		],
	},

	{
		name: "banpool",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Banpool main command",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "create",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Creates a banpool",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "name",
						type: ApplicationCommandOptionTypes.STRING,
						description: "The banpool name",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "delete",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Deletes the selected banpool",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "name",
						type: ApplicationCommandOptionTypes.STRING,
						description: "The name of the banpool that should be deleted",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "info",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Returns information about the selected banpool",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "name",
						type: ApplicationCommandOptionTypes.STRING,
						description: "The name of the banpool that should be info'd",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "invite",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Creates a one-time invite for the selected banpool",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "name",
						type: ApplicationCommandOptionTypes.STRING,
						description: "Name of the selected banpool",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "join",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Joins the selected banpool",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "code",
						type: ApplicationCommandOptionTypes.STRING,
						description: "The invite code of that banpool that you want to join",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "leave",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Leaves the selected banpool",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "name",
						type: ApplicationCommandOptionTypes.STRING,
						description: "Name of the banpool that you want to leave",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "list",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Gets a list of bannpools the server is connected to",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
			},
			{
				name: "kick",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Kicks the selected server from the selected banpool",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "guild_id",
						type: ApplicationCommandOptionTypes.STRING,
						description: "ID of the selected server",
						description_localizations: translate("slashcommand_about_description"),

						required: true,
					},
					{
						name: "name",
						type: ApplicationCommandOptionTypes.STRING,
						description: "The name of the selected banpool",
						description_localizations: translate("slashcommand_about_description"),

						required: true,
					},
				],
			},
		],
	},
	{
		name: "configure",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Configure main command",
		description_localizations: translate("slashcommand_about_description"),
	},
	{
		name: "settings",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Get the settings for the server",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
	},
	{
		name: "messageclear",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Clears X amount of messages from the database in the server",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "days",
				type: ApplicationCommandOptionTypes.INTEGER,
				description: "The amount of days of messages to clear",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
		],
	},

	{
		name: "avatar",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Gets a users avatar picture",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "user",
				type: ApplicationCommandOptionTypes.USER,
				description: "The user who's avatar you want to retrieve",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "id",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Parses Discord IDs from the provided text",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "text",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The text you want to parse Discord IDs from",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
		],
	},
	{
		name: "remind",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Reminder main command",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "list",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Returns a list of all your current active reminders",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
			},
			{
				name: "remove",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Removes the selected reminder",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "reminder",
						type: ApplicationCommandOptionTypes.INTEGER,
						description: "The ID of the reminder you want to remove",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "set",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Sets a reminder",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "duration",
						type: ApplicationCommandOptionTypes.STRING,
						description: "The duration after which you should receive the reminder",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
					{
						name: "reminder",
						type: ApplicationCommandOptionTypes.STRING,
						description: "The reminder message",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
		],
	},
	{
		name: "jumbo",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Sends a bigger version of the given emote(s)",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "emojis",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The emoji(s) you want to return in their jumbo version",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
		],
	},
	{
		name: "permissions",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Gets permission names from a permission number",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "permissions",
				type: ApplicationCommandOptionTypes.INTEGER,
				description: "The permission number",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
		],
	},

	{
		name: "archive",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Archive commands",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "channel",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Archive a channel",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "channel",
						type: ApplicationCommandOptionTypes.CHANNEL,
						description: "The channel to archive",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
						channel_types: [
							ApplicationCommandOptionsChannelTypes.GUILD_NEWS,
							ApplicationCommandOptionsChannelTypes.GUILD_NEWS_THREAD,
							ApplicationCommandOptionsChannelTypes.GUILD_PRIVATE_THREAD,
							ApplicationCommandOptionsChannelTypes.GUILD_PUBLIC_THREAD,
							ApplicationCommandOptionsChannelTypes.GUILD_TEXT,
						],
					},
				],
			},
			{
				name: "user",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Archive a user",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "user",
						type: ApplicationCommandOptionTypes.USER,
						description: "The user to archive",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
		],
	},

	{
		name: "ban",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Bans or forcebans a user from the server",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "user",
				type: ApplicationCommandOptionTypes.USER,
				description: "The user that should be banned",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason behind the ban",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "cleanban",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Bans a user and removes all their contexts from the server",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "member",
				type: ApplicationCommandOptionTypes.USER,
				description: "The member that should be banned",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason behind the ban",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "crossban",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Cross-bans the selected user from all connected banpools",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "member",
				type: ApplicationCommandOptionTypes.USER,
				description: "The user that should be cross-banned from all connected banpools",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason for the ban",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
		],
	},
	{
		name: "deafen",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Deafens a member from a Voice Channel they're connected to",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "member",
				type: ApplicationCommandOptionTypes.USER,
				description: "The member that should be deafened",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason behind the deafen",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "infraction",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Manages a given users infractions",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "claim",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Claim responsibility over the provided infraction",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "infraction",
						type: ApplicationCommandOptionTypes.INTEGER,
						description: "The infraction ID",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "info",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Returns more information about the provided information",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "infraction",
						type: ApplicationCommandOptionTypes.INTEGER,
						description: "The infraction ID",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "modsearch",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Searches the database for any infractions where the provided user is the moderator",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "user",
						type: ApplicationCommandOptionTypes.USER,
						description: "The user that should be used as a query",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "offendersearch",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Searches the database for infractions where the selected user is marked as the offender",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "user",
						type: ApplicationCommandOptionTypes.USER,
						description: "The user that should be used as a query",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "remove",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Removes the selected infraction from the database",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "infraction",
						type: ApplicationCommandOptionTypes.INTEGER,
						description: "The infraction ID",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "search",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Searches the database for any infractions where the selected user is the moderator or offender",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "user",
						type: ApplicationCommandOptionTypes.USER,
						description: "The user that should be used as the query",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "update",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Updates the selected infraction with the new provided reason",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "infraction",
						type: ApplicationCommandOptionTypes.INTEGER,
						description: "The ID of the infraction that should be updated",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
					{
						name: "reason",
						type: ApplicationCommandOptionTypes.STRING,
						description: "The new updated reason behind the infraction",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
		],
	},
	{
		name: "kick",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Kicks the selected member from the server",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "member",
				type: ApplicationCommandOptionTypes.USER,
				description: "The member that should be kicked",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason behind the kick",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "lockdown",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Locks/unlocks a selected channel",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "channel",
				type: ApplicationCommandOptionTypes.CHANNEL,
				description: "The channel that should be locked/unlocked",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
				channel_types: [
					ApplicationCommandOptionsChannelTypes.GUILD_NEWS,
					ApplicationCommandOptionsChannelTypes.GUILD_NEWS_THREAD,
					ApplicationCommandOptionsChannelTypes.GUILD_PRIVATE_THREAD,
					ApplicationCommandOptionsChannelTypes.GUILD_PUBLIC_THREAD,
					ApplicationCommandOptionsChannelTypes.GUILD_TEXT,
				],
			},
			{
				name: "locked",
				type: ApplicationCommandOptionTypes.BOOLEAN,
				description: "Whether the channel should be locked or not",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
		],
	},
	{
		name: "multiban",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Bans or forcebans multiple people from a server",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "users",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The users that should be banned separated by a space",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason behind the ban",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "multikick",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Kicks multiple people from a server",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "users",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The users that should be kicked separated by a space",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason behind the kick",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "multiunban",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Unbans multiple people from a server",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "users",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The users that should be unbanned separated by a space",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason behind the unban",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "multiwarn",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Warns multiple selected users",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "users",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The users that should be warned separated by a space",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason behind the warn",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "mute",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Mutes the selected user for the specified amount of time",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "member",
				type: ApplicationCommandOptionTypes.USER,
				description: "The member that should be muted",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "duration",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The duration for which the should be muted for",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason behind the mute",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "nickname",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Nicknames a user from the current server",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "member",
				type: ApplicationCommandOptionTypes.USER,
				description: "The member that should be nicknamed",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "nickname",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The selected user's new nickname",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason behind the nickname change",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "prune",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Prune users from the server",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "days",
				type: ApplicationCommandOptionTypes.NUMBER,
				description: "How many days to prune from",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "roles",
				type: ApplicationCommandOptionTypes.STRING,
				description: "Roles to include in the prune",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "Reason for the prune",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "purge",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Purge main command",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "all",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Purges the selected amount of messages in the given channel",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "amount",
						type: ApplicationCommandOptionTypes.INTEGER,
						description: "The amount of messages that should be fetched from the last sent message",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "between",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Purges all messages between the two given messages",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "message1",
						type: ApplicationCommandOptionTypes.STRING,
						description: "The first message",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
					{
						name: "message2",
						type: ApplicationCommandOptionTypes.STRING,
						description: "The second message",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "bots",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Purges the selected amount of messages sent from bot users",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "amount",
						type: ApplicationCommandOptionTypes.INTEGER,
						description: "The amount of messages that should be fetched from the last sent message",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "contains",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Purges the selected amount of messages containing the provided query",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "query",
						type: ApplicationCommandOptionTypes.STRING,
						description: "The query that the fetched messages must have",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
					{
						name: "amount",
						type: ApplicationCommandOptionTypes.INTEGER,
						description: "The amount of messages that should be fetched from the last sent message",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "embeds",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Purges the selected amount of messages if the message contains an embed",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "amount",
						type: ApplicationCommandOptionTypes.INTEGER,
						description: "The amount of messages that should be fetched from the last sent message",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "emojis",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Purges the selected amount of messages if the message contains an emoji",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "amount",
						type: ApplicationCommandOptionTypes.INTEGER,
						description: "The amount of messages that should be fetched from the last sent message",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "images",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Purges the selected amount of messages if the message contains an image",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "amount",
						type: ApplicationCommandOptionTypes.INTEGER,
						description: "The amount of messages that should be fetched from the last sent message",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "until",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Purges messages until a message",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "message",
						type: ApplicationCommandOptionTypes.STRING,
						description: "The message to purge until",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
			{
				name: "user",
				type: ApplicationCommandOptionTypes.SUB_COMMAND,
				description: "Purges the selected amount of messages from the selected member",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				options: [
					{
						name: "member",
						type: ApplicationCommandOptionTypes.USER,
						description: "The user who's messages should be purged",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
					{
						name: "amount",
						type: ApplicationCommandOptionTypes.INTEGER,
						description: "The amount of messages that should be fetched from the last sent message",
						name_localizations: translate("slashcommand_about_name"),
						description_localizations: translate("slashcommand_about_description"),
						required: true,
					},
				],
			},
		],
	},
	{
		name: "slowmode",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Sets a slowmode to the selected channel",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "duration",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The duration the slowmode should be set to",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "channel",
				type: ApplicationCommandOptionTypes.CHANNEL,
				description: "The channel where the slowmode should be edited",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
				channel_types: [
					ApplicationCommandOptionsChannelTypes.GUILD_NEWS,
					ApplicationCommandOptionsChannelTypes.GUILD_NEWS_THREAD,
					ApplicationCommandOptionsChannelTypes.GUILD_PRIVATE_THREAD,
					ApplicationCommandOptionsChannelTypes.GUILD_PUBLIC_THREAD,
					ApplicationCommandOptionsChannelTypes.GUILD_TEXT,
				],
			},
		],
	},
	{
		name: "softban",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Bans and immediately unbans the selected member from the server",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "member",
				type: ApplicationCommandOptionTypes.USER,
				description: "The user that should be soft-banned",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason behind the soft-ban",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "tempban",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Temporarily bans the selected member from the server",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "member",
				type: ApplicationCommandOptionTypes.USER,
				description: "The member that should be temp-banned",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "duration",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The duration the selected user should be banned for",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason behind the tempban",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "unban",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Unban a user from the server",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "user",
				type: ApplicationCommandOptionTypes.USER,
				description: "The user that should be unbanned",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason behind the unban",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "undeafen",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Undeafens a member from a Voice Channel they're connected to",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "member",
				type: ApplicationCommandOptionTypes.USER,
				description: "The member that should be undeafened",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason behind the undeafen",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "unmute",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Unmutes the selected member",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "member",
				type: ApplicationCommandOptionTypes.USER,
				description: "The member that should be unmuted",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason behind the unmute",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "verification",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Changes the server verification level",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
	},
	{
		name: "warn",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Warns the selected server member",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "member",
				type: ApplicationCommandOptionTypes.USER,
				description: "The member that should be warned",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
			{
				name: "reason",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The reason behind the warning",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: false,
			},
		],
	},
	{
		name: "snowflake",
		type: ApplicationCommandType.CHAT_INPUT,
		description: "Gets information about a given snowflake",
		name_localizations: translate("slashcommand_about_name"),
		description_localizations: translate("slashcommand_about_description"),
		options: [
			{
				name: "id",
				type: ApplicationCommandOptionTypes.STRING,
				description: "The snowflake you want to check",
				name_localizations: translate("slashcommand_about_name"),
				description_localizations: translate("slashcommand_about_description"),
				required: true,
			},
		],
	},
];

export const UserCommand: ApplicationCommand[] = [];

export const MessageCommand: ApplicationCommand[] = [
	{
		name: "Warn",
		type: ApplicationCommandType.MESSAGE,
		description: "",
	},
	{
		name: "Quick Mute (1h)",
		type: ApplicationCommandType.MESSAGE,
		description: "",
	},
	{
		name: "List all Infractions",
		type: ApplicationCommandType.MESSAGE,
		description: "",
	},
	{
		name: "Clean All Messages",
		type: ApplicationCommandType.MESSAGE,
		description: "",
	},
];
