export enum UserHandle {
	SUCCESS,
	CANNOT_ACTION_SELF,
	CANNOT_ACTION_OWNER,
	CANNOT_ACTION_ROLE_EQUAL,
	CANNOT_ACTION_BOT_SELF,
	CANNOT_ACTION_ROLE_HIGHER,
	CANNOT_ACTION_USER_ROLE_EQUAL_BOT,
	CANNOT_ACTION_USER_ROLE_HIGHER_BOT,
}
